Repository CodeDredd/laravel-soap, pull requests merged in 2020-10, with the labels that each got.

#64 Support Laravel v8
  composer.json
Labels: feature

#68 refactor(1.0): Making own branch for v1.x
  .github/workflows/releaseDrafter.yml
  README.md
  composer.json
  composer.lock
Labels: chore, dependencies

#69 refactor(1.0): Laravel 8 Suppport Updates
  composer.json
  composer.lock
Labels: BREAKING CHANGE, dependencies, feature

#67 [BREAKING CHANGE] Support laravel 8 (again - sorry!)
  composer.json
Labels: BREAKING CHANGE, dependencies

#70 refactor(2.0): Guzzle 7 Support
  composer.lock
  src/SoapClient.php
Labels: chore, dependencies
