Repository CodeDredd/laravel-soap, pull requests merged in 2021-02, with the labels that each got.

#105 Make basic auth configurable via config
  src/SoapClient.php
Labels: bug

#106 Change method visibility
  src/SoapClient.php
Labels: feature

#107 Feature/take changes
  .github/workflows/releaseDrafter.yml
  .github/workflows/tests.yml
  src/SoapClient.php
Labels: bug, feature

#108 Allow client class configuration
  docs/client/configuration.md
  src/SoapFactory.php
  tests/Fixtures/CustomSoapClient.php
  tests/Unit/SoapClientTest.php
Labels: feature
